### ISSUE TITLE
Oops, an error occurred!

### ISSUE THREAD

**Issue by nitsan-technologies** [nitsan-technologies/ns_news_advancedsearch#12]
Hello,

after installing ns_news_advancedsearch [2.0.4](https://www.vhs-sh.de/typo3/module/tools/ExtensionmanagerExtensionmanager?token=4f62b5203fcf28585ef9546053c0f0fc6721415d&tx_extensionmanager_tools_extensionmanagerextensionmanager%5BextensionKey%5D=ns_news_advancedsearch&tx_extensionmanager_tools_extensionmanagerextensionmanager%5BreturnTo%5D=index&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Baction%5D=showAllVersions&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Bcontroller%5D=List) in Typo3 11 System I get following error

503
Oops, an error occurred!
array_splice(): Argument #1 ($array) must be of type array, null given

Any ideas?

**Comment by pradeepnitsan** [comment]
Hello,

I have fixed this bug and released the new version 2.0.5

Thanks

**Comment by KaiBroenstrup** [comment]
Hi, but in the latest Version 12 with Typo3 v12 this bug is back. Any ideas? 
`(1/1) TypeError
array_splice(): Argument #1 ($array) must be of type array, null given

in /html/live/vendor/georgringer/news/Classes/Utility/ClassCacheManager.php line 173`

**Comment by nitsan-technologies** [comment]
Hello @KaiBroenstrup 

Greetings of the day!

Thank you for giving the feedback. We have fixed this issue and released the new version 12.0.1

Thanks!
Team NITSAN
